apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: khulnasoft-k8s-scanner
  labels:
    {{- include "khulnasoft-k8s-scanner.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: khulnasoft-k8s-scanner
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}