apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "khulnasoft-k8s-scanner.fullname" . }}
  labels:
    {{- include "khulnasoft-k8s-scanner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "khulnasoft-k8s-scanner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "khulnasoft-k8s-scanner.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "khulnasoft-k8s-scanner.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - -mgmt-console-url={{ required "managementConsoleUrl is required" .Values.managementConsoleUrl }}
          - -mgmt-console-port={{ required "managementConsolePort is required" .Values.managementConsolePort }}
          - -cluster-name={{ required "clusterName is required" .Values.clusterName }}
          - -debug={{ .Values.debug }}
          env:
          - name: KHULNASOFT_KEY
            valueFrom:
              secretKeyRef:
                name: "khulnasoft-key"
                key: "khulnasoft-key"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
