{{- if .Values.createKhulnasoftKeySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: khulnasoft-key
  labels:
    {{- include "khulnasoft-k8s-scanner.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- if .Values.khulnasoftKey }}
  khulnasoft-key: "{{ .Values.khulnasoftKey | b64enc }}"
{{- else }}
  khulnasoft-key: ""
{{- end }}
{{- end }}